config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "public#home"
  get 'public/home'
  authenticated :user do
    resources :profile
    resources :date
    resources :training do
      member do
        get 'chart', to: 'chart#index'
        post 'chart', to: 'chart#index'
      end
    end
    post '/training/:id', to: 'training#create', as: 'create_training'
    resources :ranking
  end
  
  devise_for :users, controllers: 
  { 
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/controllers/training_controller.rb
class TrainingController < ApplicationController
  before_action :authenticate_user!
  before_action :show, only: [:create]

  layout false

  def show    
    @user = get_current_logged_in_user
    @pumpups = @user.pumpups
    @fileDF = generatePDF
  end

  def generatePDF
    respond_to do |format|
      format.html
      format.pdf do
        pdf = Prawn::Document.new

        pdf.font_families["pdfFont"] = {
          normal: "#{Rails.root}/app/assets/fonts/CaviarDreams.ttf"
        }

        pdf.font "pdfFont"

        pdf.text "WYKONANA ILOŚĆ SERII I POWTÓRZEŃ POMPKÓW WZGLĘDEM DATY", size: 20, align: :center
        pdf.move_down 30
  
        pdfDate = []
        pdfDate << ["SERIA", "POWTÓRZENIA", "DATA"]

        @pumpups.each do |pumpup|
          pdfDate << [pumpup.series, pumpup.rep, pumpup.date]
        end
       
        pdf.table(pdfDate, header: true, cell_style: { border_width: 0.7, padding_left: 50, padding_right: 50, align: :center}, position: :center)
        pdf.number_pages "STRONA <page>", at: [pdf.bounds.right - 70, pdf.bounds.bottom]

        send_data pdf.render, type: "application/pdf", disposition: "inline"
      end
    end
  end

  def new
    @pumpup = Pumpup.new
  end

  def create
    @pumpup = @user.pumpups.create(pumpup_params)
    if @user.save
      redirect_to training_path(@user)
    else
      flash[:error] = @pumpup.errors[:date].first if @pumpup.errors[:date].any?

      if @pumpup.errors[:series].any?
        flash[:error] += "\n" if flash[:error].present?
        flash[:error] = "" if flash[:error].nil?
        flash[:error] += @pumpup.errors[:series].first.to_s if @pumpup.errors[:series].any?
      end

      if @pumpup.errors[:rep].any?
        flash[:error] += "\n" if flash[:error].present?
        flash[:error] = "" if flash[:error].nil?
        flash[:error] += @pumpup.errors[:rep].first.to_s if @pumpup.errors[:rep].any?
      end
      redirect_to training_path(@user)
    end
  end

  private

  def get_current_logged_in_user
      user_id = current_user.id
      User.find_by(id: user_id)
  end

  def pumpup_params
    params.require(:pumpup).permit(:series, :rep, :date)
  end
end

app/helpers/training_helper.rb
module TrainingHelper
end

app/views/training/show.html.erb
<head>
    <%= stylesheet_link_tag "training" %>
    <style>
    @font-face 
    {
      font-family: "CaviarDreams";
      src: url("fonts/CaviarDreams.ttf");
    }
    @font-face 
    {
      font-family: "Sunday";
      src: url("fonts/Sunday.otf");
    }
</style>
<strong>
   <%= link_to "LOGGER POMPEK", profile_path(current_user.id), class: "home_page_on_profile_page" %>
</strong>
</head>
<body>
    <script>
        function ShowNagivationVertical() 
        {
            if (document.getElementById("nagivationVertical").style.display === "none" || document.getElementById("nagivationVertical").style.display === "") 
            {
                document.getElementById("nagivationVertical").style.display = "block";
            } 
            else 
            {
                document.getElementById("nagivationVertical").style.display = "none";
            }
        }
        function AddTraining() 
        {
            document.getElementById("blockBackground").style.display = "block";
        } 

        document.getElementById("nagivationVertical").addEventListener("click", onClick);
        document.getElementById("blockBackground").addEventListener("click", onClick);
    </script>
    <div class="nagivationHorizontal">
    </div>
    <button onclick="ShowNagivationVertical()" class="showNavVer"><%= image_tag("icons8-menu-50.png", :alt => "icon", class: "icon") %></button></li>
    
    <div id="nagivationVertical">
        <div class="dateProfile">
            <h1 class="helloProfile">Witaj <%= @user.name %> <%= @user.surname %></h1>
            <h3 class="nickProfile">jako <%= @user.nick %></h3>
        </div
        <ul class="list_button">
            <li class="list_li"><%= link_to "PROFIL", date_path(@user.id), class: "buttonNavVer" %></li>
            <li class="list_li"><%= link_to "TRENING", training_path(@user.id), class: "buttonNavVer" %></li>>
            <li class="list_li"><%= link_to "RANKING", ranking_path(@user.id), class: "buttonNavVer" %></li>
            <li class="list_li"><%= button_to 'WYLOGUJ SIĘ', destroy_user_session_path, method: :delete, class: "buttonNavVer" %></li>
        </ul>
    </div>
    <div class="blockImage">
        <%= image_tag("profile.png", :alt => "profile", class: "profile") %>

        <div class="panelUser">
            <%= link_to "TRENING", training_path(@user.id), class: "panel" %>
            <h1 class="nameTable">WYKONANA ILOŚĆ SERII I POWTÓRZEŃ POMPEK WZGLĘDEM DATY</h1>
            <table>
            <tr>
                <th>SERIA</th>
                <th>POWTÓRZENIA</th>
                <th>DATA</th>
            </tr>
            <% @pumpups.each do |pumpup| %>
                <tr>
                    <th><%= pumpup.series %></th>
                    <th><%= pumpup.rep %></th>
                    <th><%= pumpup.date %></th>
                </tr>
            <% end %>
          </table>

          <div class="error">
          <% if flash[:error].present? %>
              <p><%= simple_format(flash[:error]) %></p>
          <% end %>
          </div>

        <%= link_to "POKAŻ PDF", url_for(format: :pdf, controller: 'training', action: 'show', id: @user.id), class: "PDF" %>
        <%= button_to 'POKAŻ WYKRES', chart_training_path, formtarget: "_blank", class: "buttonChart" %>
        <div class="posButton"><button onclick="AddTraining()" class="addTraining">DODAJ TRENING</button></div> 
        </div>
    </div>
        <div id="blockBackground">
        <h2 id="nameForm">Dodaj trening z robienia pompek</h2>
            <div class="add">
                <%= form_with model: [ @user, @user.pumpups.build ], url: create_training_path, metod: :post do |form| %>
                <p>
                    <%= form.number_field :rep, placeholder: "POWTÓRZENIA", class: "field" %>
                </p>
                <p>
                    <%= form.number_field :series, placeholder: "SERIA", class: "field" %>
                </p>

                <p>
                <%= form.date_field :date, placeholder: "DATA", class: "field" %>
                </p>
                <p>
                    <%= form.submit :DODAJ, class: "button_form" %>
                </p>
                <p>
                    <%= link_to "WRÓĆ", training_path(@user.id), class: "positionButton" %> 
                </p>
                <% end %>
            </div>
        </div>
</body>