config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "public#home"
  get 'public/home'
  authenticated :user do
    resources :profile
    resources :date
    resources :training do
      member do
        get 'chart', to: 'chart#index'
        post 'chart', to: 'chart#index'
      end
    end
    post '/training/:id', to: 'training#create', as: 'create_training'
    resources :ranking
  end
  
  devise_for :users, controllers: 
  { 
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController
  before_action :authenticate_user!

  layout false

  def show
      @user = get_current_logged_in_user
      @top5 = find_top5
      @top4 = find_top4
      @top3 = find_top3
      @top5_with_rep = find_top5_with_rep
  end

  private

  def find_top5_with_rep
    User.joins(:pumpups).where(pumpups: { date: Time.now.beginning_of_week..Time.now.end_of_week }).group('users.id').order('SUM(pumpups.rep) DESC').limit(5)
  end

  def find_top5
    User.joins(:pumpups).where(pumpups: { date: Time.now.beginning_of_week..Time.now.end_of_week }).select('users.*, SUM(pumpups.series * pumpups.rep) AS result').group('users.id').order('result DESC').limit(5)
  end

  def find_top4
    User.joins(:pumpups).group('users.id').order('SUM(pumpups.series) DESC').limit(4)
  end

  def find_top3
    User.joins(:pumpups).where(pumpups: { date: Time.now.beginning_of_month..Time.now.end_of_month }).group('users.id').order('COUNT(pumpups.id) DESC').limit(3)
  end

  def get_current_logged_in_user
      user_id = current_user.id
      User.find_by(id: user_id)
  end
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/views/ranking/show.html.erb
<head>
    <%= stylesheet_link_tag "ranking" %>
    <style>
    @font-face 
    {
      font-family: "CaviarDreams";
      src: url("fonts/CaviarDreams.ttf");
    }
    @font-face 
    {
      font-family: "Sunday";
      src: url("fonts/Sunday.otf");
    }
</style>
<strong>
   <%= link_to "LOGGER POMPEK", profile_path, class: "home_page_on_profile_page" %>
</strong>
</head>
<body>
    <script>
        function ShowNagivationVertical() 
        {
            if (document.getElementById("nagivationVertical").style.display === "none" || document.getElementById("nagivationVertical").style.display === "") 
            {
                document.getElementById("nagivationVertical").style.display = "block";
            } 
            else 
            {
                document.getElementById("nagivationVertical").style.display = "none";
            }
        }
    </script>
    <%= image_tag("profile.png", :alt => "profile", class: "profile") %>

    <div class="nagivationHorizontal">
    </div>

    <button onclick="ShowNagivationVertical()" class="showNavVer"><%= image_tag("icons8-menu-50.png", :alt => "icon", class: "icon") %></button></li>

    <div id="nagivationVertical">
        <div class="dateProfile">
            <h1 class="helloProfile">Witaj <%= @user.name %> <%= @user.surname %></h1>
            <h3 class="nickProfile">jako <%= @user.nick %></h3>
        </div
        <ul class="list_button">
            <li class="list_li"><%= link_to "PROFIL", date_path(@user.id), class: "buttonNavVer" %></li>
            <li class="list_li"><%= link_to "TRENING", training_path(@user.id), class: "buttonNavVer" %></li>
            <li class="list_li"><%= link_to "RANKING", ranking_path(@user.id), class: "buttonNavVer" %></li>
            <li class="list_li"><%= button_to 'WYLOGUJ SIĘ', destroy_user_session_path, method: :delete, class: "buttonNavVer" %></li>
        </ul>
    </div>

    <%= link_to "RANKING", ranking_path(@user.id), class: "panel" %>
        
    <div class="top_user">
        <h1>TOP 5</h1>
        <h3>którzy pompują najwięcej powtórzeń w tygodniu</h3>
        <% if @top5_with_rep.empty? %>
            <p>Ranking jest pusty.</p>
        <% else %>
            <ol>
            <% @top5_with_rep.each do |person| %>
                <li>
                    <p><%= person.name %> <%= person.surname %></p>
                </li>
            <% end %>
        <% end %>
        </ol>
        <h1>TOP 5</h1>
        <h3>którzy pompują najwięcej w tygodniu</h3>
        <% if @top5.empty? %>
            <p>Ranking jest pusty.</p>
        <% else %>
            <ol>
            <% @top5.each do |person| %>
                <li>
                    <p><%= person.name %> <%= person.surname %></p>
                </li>
            <% end %>
        <% end %>
        </ol>
        <h1>TOP 4</h1>
        <h3>którzy pompują najwięcej powtórzeń</h3>
        <% if @top4.empty? %>
            <p>Ranking jest pusty.</p>
        <% else %>
            <ol>
            <% @top4.each do |person| %>
                <li>
                    <p><%= person.name %> <%= person.surname %></p>
                </li>
            <% end %>
        <% end %>
        </ol>
        <h1>TOP 3</h1>
        <h3>którzy pompują najwięcej treningów w miesiącu</h3>
        <% if @top3.empty? %>
            <p>Ranking jest pusty.</p>
        <% else %>
            <ol>
            <% @top3.each do |person| %>
                <li>
                    <p><%= person.name %> <%= person.surname %></p>
                </li>
            <% end %>
        <% end %>
        </ol>
    </div>
</body>